rarityData = [
    //----------------------------------BASIC-----------------------------
    {
        type: 1,
        rarity: 1,
        amt: 1,
        distMult: 100,
        hb: 10,
    },
    {
        type: 1,
        rarity: 2,
        amt: 1,
        distMult: 100,
        hb: 10,
    },
    {
        type: 1,
        rarity: 3,
        amt: 1,
        distMult: 100,
        hb: 10,
    },
    {
        type: 1,
        rarity: 4,
        amt: 1,
        distMult: 100,
        hb: 10,
    },
    {
        type: 1,
        rarity: 5,
        amt: 1,
        distMult: 100,
        hb: 10,
    },
    {
        type: 1,
        rarity: 6,
        amt: 6,
        distMult: 100,
        hb: 10,
    },
    {
        type: 1,
        rarity: 7,
        amt: 1,
        distMult: 100,
        hb: 10,
    },
    {
        type: 1,
        rarity: 8,
        amt: 1,
        distMult: 100,
        hb: 10,
    },
    //-------------------------------------------LIGHT--------------------------------
    {
        type: 2,
        rarity: 1,
        amt: 1,
        distMult: 110,
        hb: 10,
    },
    {
        type: 2,
        rarity: 2,
        amt: 1,
        distMult: 110,
        hb: 10,
    },
    {
        type: 2,
        rarity: 3,
        amt: 2,
        distMult: 120,
        hb: 10,
    },
    {
        type: 2,
        rarity: 4,
        amt: 3,
        distMult: 120,
        hb: 10,
    },
    {
        type: 2,
        rarity: 5,
        amt: 3,
        distMult: 120,
        hb: 10,
    },
    {
        type: 2,
        rarity: 6,
        amt: 5,
        distMult: 120,
        hb: 10,
    },
    {
        type: 2,
        rarity: 7,
        amt: 5,
        distMult: 120,
        hb: 10,
    },
    {
        type: 2,
        rarity: 8,
        amt: 5,
        distMult: 120,
        hb: 16,
    }
];